### ISSUE TITLE
Thoughts on failures if ruleset fails

### ISSUE THREAD

**Issue by jrcryer** [alappe/grunt-phpmd#2]
Hi,

Currently the task doesn't fail if the phpmd identifies issues.  What are your thoughts on making the task fail?

Cheers,

James

**Comment by alappe** [comment]
Hey James,

I'm on the road, so I can't look into it deeply. It should only ignore the fail on exit code 2, which is documented on http://phpmd.org/documentation/index.html#exit-codes

Because md-violations are no criteria for me to fail it, I only want to get them documented. But I could change that to a configuration setting… would that help you?

Regards
Andy

**Comment by jrcryer** [comment]
Cool - understand where you are coming from with this.  I've seen your pull request from other repo's for grunt-phpcs etc.

I'll see if I can keep it all in sync as this makes sense.

Cheers,

James

**Comment by joerx** [comment]
I would like to see at least some warning issued to the output. This way I could configure my CI server (Jenkins) to parse the build output for that string and set my build to unstable.

**Comment by adam187** [comment]
+1 I would also try to use this task for CI and in current state it's imposible. 
I can prepere some pull request with additional configuration option if you don't have time for it @alappe.

**Comment by jrcryer** [comment]
@joerx and @adam187 - PRs sound excellent.  Sure @alappe would appreciate it!

**Comment by alappe** [comment]
Indeed I would…

**Comment by adam187** [comment]
Ok i will prepare something on weekend. 

I think it would be best to add option `minErrorLevel` with default value of `2` so it won't break BC and when you change it to `1` it will trigger fatal for error code `1` and `2` from `phpmd` instead only form `2`. What do you think about that @alappe ?

**Comment by alappe** [comment]
Yes, sounds great…

**Comment by adam187** [comment]
@alappe Any news with this :) ?
My PR is ready for a long time https://github.com/alappe/grunt-phpmd/pull/5

**Comment by alappe** [comment]
Hey @adam187, thanks for the reminder…
