### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by paazmaya** [alappe/grunt-phpmd#3]
Fix examples to have correct syntax.

Add more usage examples for different options.

Add release history.

**Comment by alappe** [comment]
Hey @paazmaya,

I will certainly try to fix those, but could you clarify for me why a release history is needed? What is wrong with the syntax? Do you have any different examples regarding the options in mind?

Would you be willing to contribute a pull request that would solve your issues?

Best regards
Andy

**Comment by paazmaya** [comment]
Hi,
Thank you for the quick reply.

The example configuration is missing a comma, thus not valid JavaScript.

Since most of `npm` plugins provide the changelog, I have become accustomed to have it available. It would also describe the history of the project in short glance. 

I dont want to promise to provide a PR but might do it in case I have time....

**Comment by paazmaya** [comment]
Closing as "possibly out of date". Goodbye.
