### ISSUE TITLE
Exclude, and "." not working for me.

### ISSUE THREAD

**Issue by saas786** [alappe/grunt-phpmd#7]
Hi,

I have been messing with this configuration since last several days and no luck.

Rules: https://github.com/FlagshipWP/compass/blob/develop/phpmd.xml
Task: 

```
module.exports = {
    options: {
        reportFormat: 'html',
        reportFile: '<%=builddir%>/logs/phpmd-report.html',
        strict: true,
        rulesets: '<%=builddir%>/phpmd.xml',
        exclude:'node_modules'
    },
    theme: {
        dir: '.'
    }
}
```

It just throws **Fatal Error**

If I do same in cmd, like this:

```
E:\wamp\personal\wp-content\themes\basic>phpmd . html ./phpmd.xml --reportfile ./logs/phpmd-report.html --exclude node_modules
```

I get this error.

```
RecursiveDirectoryIterator::__construct(E:\wamp\personal\wp-content\themes\basic\node_modules\grunt-contrib-imagemin
\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node
_modules\bin-wrapper\node_modules\download\node_modules\rc,

E:\wamp\personal\wp-content\themes\basic\node_modules\gru
nt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_mo
dules\gifsicle\node_modules\bin-wrapper\node_modules\download\node_modules\rc):
The system cannot find the path specified. (code: 3)
```

Where as if I just do this,

**phpmd.js**

```
module.exports = {
    options: {
        reportFormat: 'html',
        reportFile: '<%=builddir%>/logs/phpmd-report.html',
        strict: true,
        rulesets: '<%=builddir%>/phpmd.xml',
        exclude:''
    },
    theme: {
        dir: 'functions'
    }
}
```

and / or

```
E:\wamp\personal\wp-content\themes\basic>phpmd functions html ./phpmd.xml --reportfile ./logs/phpmd-report.html
```

it works as well.

Can you help me sort out the issue.

**Comment by alappe** [comment]
Hey @saas786,

have you tried it like the following?

``` js
module.exports = {
    options: {
        reportFormat: 'html',
        reportFile: '<%=builddir%>/logs/phpmd-report.html',
        strict: true,
        rulesets: '<%=builddir%>/phpmd.xml'
    },
    dir: 'functions'
}
```

I am assuming that you're using that as a template and filling builddir somewhere else, right?

Apart from that I would need to know more about both your directory structure and the grunt code your using together with the JS above. Also have a look at the [test gruntfile that is supplied with the module](https://github.com/alappe/grunt-phpmd/blob/master/Gruntfile.coffee) for a very simple example…

Oh, and try to run it with `--verbose` and paste the output – this should show you the command the module constructed and executed, hopefully pointing out what's wrong/missing…

**Comment by saas786** [comment]
Yes @alappe I have tried that, and it works.

But if I specificy **dir** to be the build dir where my grunt file is, with **"."** it doesn't work. But it doesn't matter now anyway, I have moved all my theme files to sub directory "theme" and use it with

dir: "theme" 

and it works.

**Comment by alappe** [comment]
Glad to hear that you solved it…
